import Head from 'next/head'
import styles from '../styles/app.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JETA</title>
        <meta name="JETA" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">JETA!</a>
        </h1>
      </main>
    </div>
  )
}
